# CLIMATE CHANGE AND SUSTAINABILITY ANALYSIS
This notebook analyzes CO2 emissions, renewable energy, population and gdp

In [59]:
#IMPORTING LIBRARIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## 1.Loading the Datasets

In [127]:
# Load CSVs
renewable_df=pd.read_csv('../climate_project data/renewable_energy.csv')
population_df=pd.read_csv('../climate_project data/population.csv')
co2_df=pd.read_csv('../climate_project data/co2_emissions.csv')
gdp_df=pd.read_csv('../climate_project data/gdp_percapita.csv')

#Preview
co2_df.head()

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1750,AFG,2802560.0,NaN,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1751,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1752,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1753,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1754,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 2.Cleaning the Datasets

In [128]:
#Dropping unnecessary columns
gdp_df.drop(columns=['World regions according to OWID', 'Code'], inplace=True)
renewable_df.drop(columns=['Code'], inplace=True)
cols_to_keep=['country', 'year', 'co2', 'co2_per_capita','coal_co2', 'oil_co2', 'gas_co2',]
co2_df=co2_df[cols_to_keep].copy()

#Renaming columns
gdp_df=gdp_df.rename(columns={'Entity': 'country', 'Year': 'year', 'GDP per capita, PPP (constant 2021 international $)': 'gdp_per_capita'})
population_df= population_df.rename(columns={'Entity': 'country', 'Year': 'year', 'all years': 'population'})
renewable_df.rename(columns={'Entity': 'country', 'Year': 'year', 'Renewables (% equivalent primary energy)': 'renewable_energy_consumption'}, inplace=True)

In [129]:
#Checking for null values
print(renewable_df.isna().sum())
print(gdp_df.isna().sum())
print(population_df.isna().sum())

#Removing or filling null values
gdp_df=gdp_df.dropna(subset=['gdp_per_capita'])

country                         0
year                            0
renewable_energy_consumption    0
dtype: int64
country            0
year               0
gdp_per_capita    81
dtype: int64
country       0
year          0
population    0
dtype: int64

In [130]:
co2_df.isna().sum()

country               0
year                  0
co2               21054
co2_per_capita    24009
coal_co2          28436
oil_co2           24973
gas_co2           32177
dtype: int64

In [132]:
co2_df[co2_df['co2'].isna()]['country'].unique()

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Anguilla', 'Antarctica', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Aruba', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belize', 'Benin', 'Bermuda',
       'Bhutan', 'Bolivia', 'Bonaire Sint Eustatius and Saba',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cambodia', 'Cameroon', 'Cape Verde',
       'Central African Republic', 'Chad', 'China', 'Christmas Island',
       'Colombia', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao', 'Cyprus', 'Czechia',
       'Democratic Republic of Congo', 'Djibouti', 'Dominica',
       'Dominican Republic', 'East Timor', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'European Union (27)', 'Faroe Islands',
       'Fiji', 'Finland', 'French Polynesia', 'Gabon', 'Gambia',
       'Georgia', 'Ghana', 'Greece', 'Greenland', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'International aviation', 'International shipping',
       'International transport', 'Iran', 'Iraq', 'Ireland', 'Israel',
       'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya',
       'Kiribati', 'Kosovo', 'Kuwait', 'Kuwaiti Oil Fires', 'Kyrgyzstan',
       'Laos', 'Latvia', 'Least developed countries (Jones et al.)',
       'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein',
       'Lithuania', 'Low-income countries',
       'Lower-middle-income countries', 'Luxembourg', 'Macao',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (country)', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia',
       'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'North America',
       'North America (excl. USA)', 'North Korea', 'North Macedonia',
       'OECD (Jones et al.)', 'Oman', 'Pakistan', 'Palau', 'Palestine',
       'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
       'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda',
       'Ryukyu Islands', 'Ryukyu Islands (GCP)', 'Saint Helena',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South America',
       'South Korea', 'South Sudan', 'Sri Lanka', 'Sudan', 'Suriname',
       'Switzerland', 'Syria', 'Tajikistan', 'Tanzania', 'Thailand',
       'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda',
       'Ukraine', 'United Arab Emirates', 'Upper-middle-income countries',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vatican', 'Venezuela',
       'Vietnam', 'Wallis and Futuna', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype=object)